<header>
    <h1>MAJRD Database</h1>
    <nav>
        <div class="hyperlink-container">
            <a href="roundsearch.php">Search</a>
        </div>

        <div class="hyperlink-container">
            <a href="roundadd.php">Add</a>
        </div>

        <div class="hyperlink-container">
            <a href="viewscores.php">Scores</a>
        </div>

        <div class="hyperlink-container">
            <a href="managecompetitions.php">Competitions</a>
        </div>

        <div class="hyperlink-container">
            <a href="managearchers.php">Archers</a>
        </div>
    </nav>
</header>
